import React, { useState, useEffect, useRef, useMemo } from 'react';
import { Canvas } from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';
import { applyDevMask } from './utils/maskHelper';
import JarvisCore from './components/JarvisCore';

// ─────────────────────────────────────────────
// 🌐 Language Detection (from user input text)
// ─────────────────────────────────────────────
function detectLanguage(text) {
  if (/[\u0900-\u097F]/.test(text)) return { lang: 'hi-IN', name: 'Hindi' };
  if (/[\u0C00-\u0C7F]/.test(text)) return { lang: 'te-IN', name: 'Telugu' };
  if (/[\u0B80-\u0BFF]/.test(text)) return { lang: 'ta-IN', name: 'Tamil' };
  if (/[\u0C80-\u0CFF]/.test(text)) return { lang: 'kn-IN', name: 'Kannada' };
  if (/[\u0D00-\u0D7F]/.test(text)) return { lang: 'ml-IN', name: 'Malayalam' };
  if (/[\u0A00-\u0A7F]/.test(text)) return { lang: 'pa-IN', name: 'Punjabi' };
  if (/[\u0600-\u06FF]/.test(text)) return { lang: 'ar-SA', name: 'Arabic' };
  if (/[\u3040-\u30FF\u3400-\u4DBF\u4E00-\u9FFF]/.test(text)) return { lang: 'ja-JP', name: 'Japanese' };
  if (/[\u0400-\u04FF]/.test(text)) return { lang: 'ru-RU', name: 'Russian' };
  if (/\b(je|tu|il|elle|nous|vous|ils|bonjour|merci|oui|non|comment|pourquoi|quoi|est|une|le|la|les|des|du)\b/i.test(text)) return { lang: 'fr-FR', name: 'French' };
  if (/\b(yo|tu|el|ella|nosotros|hola|gracias|si|no|como|por|que|qué|es|un|una|los|las|del)\b/i.test(text)) return { lang: 'es-ES', name: 'Spanish' };
  if (/\b(ich|du|er|sie|wir|hallo|danke|ja|nein|wie|warum|was|ist|ein|eine|die|der|das)\b/i.test(text)) return { lang: 'de-DE', name: 'German' };
  return { lang: 'en-US', name: 'English' };
}

// ─────────────────────────────────────────────
// 🖼️ ImageCard — loading skeleton + auto-retry + lightbox
// ─────────────────────────────────────────────
function ImageCard({ src, prompt }) {
  const [status,   setStatus]   = useState('loading'); // loading | loaded | error
  const [retries,  setRetries]  = useState(0);
  const [lightbox, setLightbox] = useState(false);

  // Cache-bust on retry
  const finalSrc = useMemo(() => {
    if (retries === 0) return src;
    const sep = src.includes('?') ? '&' : '?';
    return `${src}${sep}_r=${retries}`;
  }, [src, retries]);

  const handleError = () => {
    if (retries < 5) {
      setTimeout(() => {
        setRetries(r => r + 1);
        setStatus('loading');
      }, 2500);
    } else {
      setStatus('error');
    }
  };

  return (
    <>
      {/* ── Lightbox overlay ── */}
      {lightbox && (
        <div
          onClick={() => setLightbox(false)}
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/92 backdrop-blur-md cursor-zoom-out"
        >
          <img
            src={finalSrc}
            alt={prompt}
            className="max-w-[92vw] max-h-[92vh] rounded-2xl border border-cyan-400/30 shadow-[0_0_60px_rgba(6,182,212,0.35)] object-contain"
          />
          <button
            className="absolute top-5 right-7 text-white/70 text-4xl leading-none hover:text-white hover:scale-110 transition-all"
            onClick={e => { e.stopPropagation(); setLightbox(false); }}
          >✕</button>
        </div>
      )}

      {/* ── Card body ── */}
      <div className="mt-4 flex flex-col items-center w-full">

        {/* Loading skeleton */}
        {status === 'loading' && (
          <div className="w-full max-w-sm h-64 rounded-2xl bg-gradient-to-br from-cyan-950/40 to-black/60 border border-cyan-500/25 animate-pulse flex flex-col items-center justify-center gap-4">
            <div className="w-12 h-12 border-4 border-cyan-400 border-t-transparent rounded-full animate-spin" />
            <span className="text-cyan-400/55 text-xs tracking-widest uppercase">
              {retries > 0 ? `Retrying… (${retries}/5)` : 'Generating Image…'}
            </span>
          </div>
        )}

        {/* Error state */}
        {status === 'error' && (
          <div className="w-full max-w-sm h-44 rounded-2xl bg-red-950/30 border border-red-500/30 flex flex-col items-center justify-center gap-3">
            <span className="text-3xl">⚠️</span>
            <span className="text-red-400/80 text-xs tracking-widest text-center px-4">
              Image could not load. Check your connection.
            </span>
            <button
              onClick={() => { setRetries(0); setStatus('loading'); }}
              className="mt-1 px-4 py-1.5 text-xs border border-red-400/50 text-red-300 rounded-lg hover:bg-red-900/30 transition-all"
            >↺ Retry</button>
          </div>
        )}

        {/* Actual image — invisible while loading, smooth fade-in on load */}
        <img
          key={finalSrc}
          src={finalSrc}
          alt={prompt || 'Generated by Jarvis'}
          onLoad={() => setStatus('loaded')}
          onError={handleError}
          onClick={() => status === 'loaded' && setLightbox(true)}
          className={`w-full max-w-sm rounded-2xl border border-cyan-500/30
            shadow-[0_0_22px_rgba(6,182,212,0.22)]
            transition-all duration-700
            ${status === 'loaded'
              ? 'opacity-100 cursor-zoom-in hover:shadow-[0_0_40px_rgba(6,182,212,0.55)] hover:scale-[1.025] hover:border-cyan-400/60'
              : 'opacity-0 h-0 pointer-events-none overflow-hidden'
            }`}
          style={{ filter: 'brightness(0.96) contrast(1.07) saturate(1.12)' }}
        />

        {/* Action buttons — only when loaded */}
        {status === 'loaded' && (
          <div className="flex gap-3 mt-3">
            <button
              onClick={() => setLightbox(true)}
              className="px-4 py-2 text-xs uppercase font-bold tracking-widest border border-cyan-400/50 text-cyan-300 rounded-lg hover:bg-cyan-400/15 transition-all"
            >🔍 Expand</button>
            <a
              href={finalSrc}
              download={`jarvis-img-${Date.now()}.jpg`}
              target="_blank"
              rel="noreferrer"
              className="px-4 py-2 text-xs uppercase font-bold tracking-widest border border-cyan-400 text-cyan-400 rounded-lg hover:bg-cyan-400 hover:text-black transition-all"
            >⬇ Save Image</a>
          </div>
        )}
      </div>
    </>
  );
}

// ─────────────────────────────────────────────
// 🤖 Main App
// ─────────────────────────────────────────────
export default function App() {
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [devMaskOn,  setDevMaskOn]  = useState(false);
  const [chats,      setChats]      = useState([]);
  const [inputText,  setInputText]  = useState('');

  const ws             = useRef(null);
  const chatContainerRef  = useRef(null);
  const detectedLangRef   = useRef({ lang: 'en-US', name: 'English' });
  const voiceRef          = useRef(null);

  // ── Voice init ──
  useEffect(() => {
    const setVoice = () => {
      const voices = window.speechSynthesis.getVoices();
      voiceRef.current =
        voices.find(v => (v.name.includes('Male') && v.lang.includes('en')) || v.name.includes('David') || v.name.includes('Zira') || v.lang === 'en-GB')
        || voices[0];
    };
    setVoice();
    window.speechSynthesis.onvoiceschanged = setVoice;
  }, []);

  // ── TTS output (in detected user language) ──
  const outputSpeech = (text, forceLang) => {
    if (!window.speechSynthesis) return;
    window.speechSynthesis.cancel();

    const cleanText = text.replace(/[*_#`]/g, '');
    const lang      = forceLang || detectedLangRef.current.lang || 'en-US';
    const utterance = new SpeechSynthesisUtterance(cleanText);
    utterance.lang  = lang;

    utterance.onstart = () => setIsSpeaking(true);
    utterance.onend   = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);

    const voices      = window.speechSynthesis.getVoices();
    const langPrefix  = lang.split('-')[0];
    const matched     = voices.find(v => v.lang === lang) || voices.find(v => v.lang.startsWith(langPrefix));

    utterance.voice = matched || voiceRef.current;
    utterance.pitch = 0.9;
    utterance.rate  = 1.05;

    window.speechSynthesis.speak(utterance);
  };

  // ── WebSocket ──
  useEffect(() => {
    ws.current = new WebSocket('ws://localhost:8000/ws/jarvis');

    ws.current.onopen  = () => console.log('[WS] Connected');
    ws.current.onerror = err => console.error('[WS] Error', err);
    ws.current.onclose = () => console.log('[WS] Closed');

    ws.current.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        setChats(prev => [...prev, data]);

        if (data.role === 'JARVIS' && data.content) {
          outputSpeech(data.content, detectedLangRef.current.lang);
        }
      } catch (err) {
        console.error('[WS] Parse error', err);
      }
    };

    return () => ws.current?.close();
  }, []);

  // ── Auto-scroll ──
  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
  }, [chats]);

  // ── Send message ──
  const handleSend = (e) => {
    if (e.key !== 'Enter' || !inputText.trim()) return;
    const trimmed  = inputText.trim();
    const detected = detectLanguage(trimmed);
    detectedLangRef.current = detected;

    setChats(prev => [...prev, { role: 'User', content: trimmed }]);

    const payload = JSON.stringify({ command: trimmed, lang: detected.lang, langName: detected.name });
    if (ws.current?.readyState === WebSocket.OPEN) {
      ws.current.send(payload);
    }
    setInputText('');
  };

  // ─────────── JSX ───────────
  return (
    <div className={`h-screen w-full transition-colors duration-500 flex flex-col overflow-hidden ${devMaskOn ? 'bg-black text-green-500 font-mono' : 'bg-[#030712] text-cyan-400 font-sans'}`}>

      {/* 3D Core Background */}
      <div className="absolute top-0 left-0 w-full h-full z-0 pointer-events-auto flex items-center justify-center">
        <Canvas camera={{ position: [0, 0, 4] }}>
          <ambientLight intensity={1} />
          <directionalLight position={[2, 5, 2]} intensity={2} />
          <JarvisCore isSpeaking={isSpeaking} />
          <OrbitControls enableZoom={false} autoRotate autoRotateSpeed={0.5} />
        </Canvas>
      </div>

      {/* UI Overlay */}
      <div className="relative z-10 flex flex-col h-full pointer-events-none">

        {/* Header */}
        <div className="flex justify-between items-center p-6 pointer-events-auto border-b border-white/5 bg-black/20 backdrop-blur-sm">
          <h1 className="text-3xl font-bold tracking-[0.2em] uppercase">
            {devMaskOn ? applyDevMask('NEXUS') : 'J.A.R.V.I.S'}
          </h1>
          <button
            onClick={() => setDevMaskOn(!devMaskOn)}
            className="px-4 py-2 border border-current rounded hover:bg-current hover:text-black transition-all font-bold uppercase tracking-widest shadow-[0_0_10px_currentColor]"
          >
            {devMaskOn ? 'Disable Mask' : 'Activate Dev Mask'}
          </button>
        </div>

        {/* Chat Panel */}
        <div
          ref={chatContainerRef}
          className="flex-1 overflow-y-auto p-6 pointer-events-auto custom-scrollbar w-full max-w-4xl mx-auto mt-4 mb-4 flex flex-col"
          style={{ maxHeight: '65vh' }}
        >
          {chats.length === 0 && (
            <div className="text-center opacity-30 mt-10 tracking-widest text-sm animate-pulse">
              {devMaskOn ? 'AWAITING_ROOT_COMMAND...' : 'AWAITING COMMAND, SIR...'}
            </div>
          )}

          {chats.map((chat, idx) => (
            <div key={idx} className={`mb-6 flex flex-col ${chat.role === 'User' ? 'items-end' : 'items-start'}`}>
              <span className="text-xs opacity-50 uppercase tracking-widest mb-1">{chat.role}</span>
              <div className={`p-4 rounded-lg backdrop-blur-md border max-w-2xl
                ${chat.role === 'User'
                  ? 'bg-cyan-900/10 border-cyan-500/20 text-white'
                  : 'bg-black/30 border-white/5 text-cyan-400'}
                ${devMaskOn ? 'border-green-500/30 text-green-400' : ''}`}>
                <p className="text-md leading-relaxed tracking-wide mb-2 whitespace-pre-wrap">
                  {devMaskOn ? applyDevMask(chat.content) : chat.content}
                </p>

                {/* ✅ Image preview for every image message */}
                {chat.imageUrl && (
                  <ImageCard src={chat.imageUrl} prompt={chat.content} />
                )}
              </div>
            </div>
          ))}
        </div>

        {/* Input Box */}
        <div className="w-full max-w-4xl mx-auto p-6 pt-0 pointer-events-auto mt-auto mb-4">
          <input
            type="text"
            value={inputText}
            onChange={e => setInputText(e.target.value)}
            onKeyDown={handleSend}
            placeholder={devMaskOn ? '> ENTER_BINARY_COMMAND' : 'Interface with J.A.R.V.I.S (Type and press Enter)...'}
            className="w-full bg-black/60 backdrop-blur-lg border border-white/10 rounded-lg py-4 px-6 outline-none focus:border-current focus:shadow-[0_0_15px_currentColor] transition-all text-lg shadow-xl"
          />
        </div>

      </div>
    </div>
  );
}